### ISSUE TITLE
Containerize the whole project

### ISSUE THREAD

**Issue by antisrdy** [GregaVrbancic/fastapi-celery#2]
Hi, thank you for the great tutorial.

Do you have any idea how we could completely containerize the project? I'm struggling with the `docker-compose.yml`, trying to containerize the API as well as the worker. Doing as in the file below doesn't run neither the API nor the worker.

```
version: "2"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:5.0.4"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"

  api:
    build:
      context: src/api_dir
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
    volumes:
      - "public:/app/public"

  worker:
    build:
      context: src/api_dir
    command: celery worker -A path.to.worker -l info -Q queue -c 2
    depends_on:
      - redis
    volumes:
      - "public:/app/public"

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  public:
    driver: local
```
